---
# tasks file for pi-hole
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Ensure Pi-hole folder is present
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Install and configure Unbound
  ansible.builtin.import_tasks: unbound.yml

- name: Install and configure Pi-hole
  ansible.builtin.import_tasks: pihole.yml
